### PR TITLE
updating dependency for mbed-hal-nordic to ^2.0.0

### PR DESCRIPTION
**Pull request by rgrover**
@0xc0170 

and the ripple effect continues.

### CODE REVIEW

**Comment by 0xc0170** [comment]
why does this depend on mbed-hal-nordic? I believe it should be mbed-hal ?

**Comment by rgrover** [comment]
@0xc0170

**Comment by 0xc0170** [comment]
+1

**Comment by rgrover** [comment]
published v2.0.2

**Pull request merged**
