### PR TITLE
PwmOut fixes

### PR DESCRIPTION
**Pull request by jacobrosenthal**
DONT MERGE YET

Working branch for fixes for #42

### CODE REVIEW

**Comment by ciarmcom** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by jrobeson** [comment]
why did you close this?

**Comment by jacobrosenthal** [comment]
Being a 16 bit timer means its going to need a very different solution to
try to eek 32bit resolution out of it.

**Comment by jrobeson** [comment]
true. guess doing another PR is better than editing this one

**Pull request closed without merging**
