### PR TITLE
reverting v1.0.5; will redo it as 2.0.0

### PR DESCRIPTION
**Pull request by rgrover**
fix for issue #21 
@marcuschangarm @0xc0170 

this will become v1.0.6, which is the same as v1.0.4
I'll release v2.0 once this is merged.

### CODE REVIEW

**Comment by rgrover** [comment]
bump @marcuschangarm @0xc0170

**Comment by marcuschangarm** [comment]
+1, Thanks!

**Comment by 0xc0170** [comment]
LGTM

**Comment by rgrover** [comment]
published v1.0.6

will submit a PR for v2.0.0

**Pull request merged**
